services:
  - type: web
    name: College-Library-Frontend
    runtime: static
    rootDir: lib_frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html